version: '3'
services:
  nginx:
    image: nginx
    networks:
      - traefik_net
    deploy:
      mode: replicated
      replicas: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx.rule=Host(`domain.com`)"
        - "traefik.http.routers.nginx.entrypoints=websecure"
        - "traefik.http.routers.nginx.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"
networks:
  traefik_net:
    external: true